// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCUop0QArFUY0adrsCSLbE2zTnifPHmXU',
    appId: '1:623533129305:web:a2f8a6d14717893ac0bb48',
    messagingSenderId: '623533129305',
    projectId: 'meeting-1-cd58f',
    authDomain: 'meeting-1-cd58f.firebaseapp.com',
    storageBucket: 'meeting-1-cd58f.appspot.com',
    measurementId: 'G-K9539MWGXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi5b2KlkbB9GdNgKCGzYjwbYXqRIZX15k',
    appId: '1:623533129305:android:9d5f6e86fe24d552c0bb48',
    messagingSenderId: '623533129305',
    projectId: 'meeting-1-cd58f',
    storageBucket: 'meeting-1-cd58f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLO8ZERyZ386bsjpCW24nO6EXhIVgWERQ',
    appId: '1:623533129305:ios:7b78e6e783ab96c3c0bb48',
    messagingSenderId: '623533129305',
    projectId: 'meeting-1-cd58f',
    storageBucket: 'meeting-1-cd58f.appspot.com',
    iosClientId: '623533129305-vb6nfer32k9bmjecckfak3s339aol073.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetingWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLO8ZERyZ386bsjpCW24nO6EXhIVgWERQ',
    appId: '1:623533129305:ios:7b78e6e783ab96c3c0bb48',
    messagingSenderId: '623533129305',
    projectId: 'meeting-1-cd58f',
    storageBucket: 'meeting-1-cd58f.appspot.com',
    iosClientId: '623533129305-vb6nfer32k9bmjecckfak3s339aol073.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetingWebApp',
  );
}
